### PR TITLE
Fix cmake rules to really install executable and libraries

### LINKED ISSUE #58: make install does not install binaries, just .pc file
```
mkdir -p build
cd build

$ cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
    -DCMAKE_C_FLAGS="$CFLAGS" \
    -DCMAKE_VERBOSE_MAKEFILE=TRUE

$ make
$ make DESTDIR=target install
…
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: … target/usr/lib/pkgconfig/libmtex2MML.pc

$ tree target/
target
└── usr
    └── lib
        └── pkgconfig
            └── libmtex2MML.pc

$ ls -1 build/
CMakeCache.txt
CMakeFiles
CTestTestfile.cmake
DartConfiguration.tcl
Makefile
Testing
cmake_install.cmake
install_manifest.txt
lexer.c
libmtex2MML.a
libmtex2MML.pc
libmtex2MML.so
libmtex2MML.so.1.3.1
mtex2MML
mtex2MML_clar
mtex2mml_export.h
parser.c
parser.h
parser.output
```

### PR DESCRIPTION
**Pull request by jirutka**
I should note that I don't have much experience with CMake, so I'm not
sure if this solution is _correct_. However, it works as expected.

Fixes #58

### CODE REVIEW

**Comment by dsisnero** [comment]
Can you merge this pull request?

**Comment by gjtorikian** [comment]
I cannot/will not merge a PR with failing CI tests.

Having said that I don't think the failures are specific to this branch, but just in case, it'll take time to investigate and fix the problem. For example, it looks like the Appveyor Windows builds are having trouble downloading flex and bison for some reason.

**Comment by gjtorikian** [comment]
Oof, and the macOS error is from a memory leak: https://github.com/gjtorikian/mtex2MML/pull/62

**Comment by gjtorikian** [comment]
Thank you for your contribution, @jirutka !

**Pull request merged**
